spring:
  cloud:
    config:
      server:
#        git:
#          uri: https://github.com/spring-cloud-samples/config-repo
        native:
          search-locations: classpath:/config
  application:
      name: @artifactId@
  profiles:
      active: native

server:
  port: 8888
