FROM registry.aliyuncs.com/com.lida/java8:latest

MAINTAINER JacobdDong@qq.com

ADD /@pom.artifactId@-@pom.version@.jar //app

EXPOSE  8888

CMD ["java","-jar","//app/@pom.artifactId@-@pom.version@.jar"]
