
server:
  port: 8761

eureka:
  server:
    enableSelfPreservation: false
  instance:
    hostname: @project.artifactId@_@project.version@
  client:
    register-with-eureka: false
    fetch-registry: false



